@startgantt
Project starts on 2025-03-28
saturday are closed
sunday are closed

[Анализ требований] starts on 2025-03-28 and ends on 2025-04-04
[Проектирование] starts on 2025-04-04 and ends on 2025-04-11
[Реализация] starts on 2025-04-11 and ends on 2025-04-25
[Модульное тестирование] starts on 2025-04-21 and ends on 2025-04-23
[Интеграционное тестирование] starts on 2025-04-23 and ends on 2025-04-25
[Приёмочное тестирование] starts on 2025-04-25 and ends on 2025-04-26
[Ввод в эксплуатацию] starts on 2025-04-26 and ends on 2025-04-29

[Анализ требований] -> [Проектирование]
[Проектирование] -> [Реализация]
[Реализация] -> [Модульное тестирование]
[Модульное тестирование] -> [Интеграционное тестирование]
[Интеграционное тестирование] -> [Приёмочное тестирование]
[Приёмочное тестирование] -> [Ввод в эксплуатацию]
@endgantt